# Setup args
init_msg: "Iudex Gundyr gym. Please make sure you start at the `Cemetry of Ash` bonfire!\n
Please make sure your keyboard settings are correct!"
cam_setup_orient: [0.378, 0.926, 0]

# StateSpace args
space_stats_low: [0, 0, 0]
space_stats_high: [454, 95, 1037]
space_coords_low:  [110., 540., -73.]
space_coords_high: [190., 640., -55.]