# Setup args
init_msg: "Vordt of the Boreal Valley gym. Please make sure your keyboard settings are correct!"
cam_setup_orient: [0.0, -1.0, 0.0]

# StateSpace coordinate boxes
coordinate_box_low:  [13., -7., -27., -3.1416]
coordinate_box_high: [42., 46., -15., 3.1416]
# Player and boss stats boxes
player_max_hp: 483
player_max_sp: 98
boss_max_hp: 1328
# Spawn info
bonfire: "Dancer of the Boreal Valley"